//pwm related
const int sys_clock = 36000000;
const int desiredfrequencyPWM = 100000; //in Hz
const int overflow_value = sys_clock/desiredfrequencyPWM;
int duty_cycle = 0;// 0 to 4096
float normalised_duty_cycle = duty_cycle/4096;
int toggle = 0;


void setup() {
  Serial.begin (115200);
  pinMode(PC13, OUTPUT);//  onboard LED
  pinMode(PB11, OUTPUT);//  forward dir pin
  pinMode(PB10, OUTPUT);//  backward dir pin
  

  Timer2.setMode(TIMER_CH1, TIMER_OUTPUTCOMPARE);
  Timer2.setPeriod(overflow_value); // in microseconds
  Timer2.setCompare(TIMER_CH1, 1);      // overflow might be small
  Timer2.attachInterrupt(TIMER_CH1, handler_PWM);

  digitalWrite(PB10, toggle);
  digitalWrite(PB11, !toggle);
}

void handler_PWM(void) {
    toggle ^= 1;
    digitalWrite(PB10, toggle);
    if(toggle==1){
      Timer2.setPeriod(overflow_value*normalised_duty_cycle);
    }
    else{
      Timer2.setPeriod(overflow_value*(1-normalised_duty_cycle));
    }
    
    //+counter*10
}



void loop() {
  Serial.println (normalised_duty_cycle);
  delay(1000); 
  normalised_duty_cycle = 0.8;// input duty cycle here
  Serial.println (normalised_duty_cycle);
  delay(1000); 
  normalised_duty_cycle = 0.4;
}
/*
    Motor Speed Control: The PWM frequency affects the motor's speed control resolution. A higher frequency allows for more precise speed control with smaller increments between different speed levels. Conversely, a lower frequency may result in fewer distinct speed levels and less precise speed control.

    Audible Noise: PWM frequency can affect the audible noise generated by the motor. Some motors emit an audible whining sound when driven by PWM signals at certain frequencies. Adjusting the PWM frequency can help minimize or shift this noise to a less noticeable frequency range.

    Motor Heating: PWM frequency can impact motor heating. Higher frequencies generally result in smoother current flow and reduced heating because the motor windings experience less time with rapidly changing current. However, excessively high frequencies may introduce additional switching losses, leading to increased heat generation.

    Torque Ripple: PWM frequency can influence torque ripple, which refers to variations in torque output during motor operation. Higher frequencies tend to reduce torque ripple, resulting in smoother motor operation. Lower frequencies, on the other hand, may introduce more noticeable torque variations.

    Efficiency: The choice of PWM frequency can affect overall motor efficiency. Finding the optimal frequency can help minimize power losses due to switching and maximize the motor's energy conversion efficiency.
    */